repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version (matches pyproject.toml constraint: >=0.12.1,<1.0)
    rev: v0.12.1
    hooks:
      # Run the linter with automatic fixes
      - id: ruff-check
        args: [--fix]
      # Run the formatter
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
