target-version = "py39"
line-length = 120  # NOTE: 88 is too short
indent-width = 4

[lint]
# Enable comprehensive but practical rule set
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
    "N",    # pep8-naming
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "T10",  # flake8-debugger
    "RET",  # flake8-return
    "TCH",  # flake8-type-checking
    "PTH",  # flake8-use-pathlib
    "RUF",  # Ruff-specific rules
    "S",    # flake8-bandit (security)
    "A",    # flake8-builtins
    "PL",   # Pylint
    "C90",  # mccabe (complexity)
    "PIE",  # flake8-pie
    "Q",    # flake8-quotes
    "RSE",  # flake8-raise
    "TRY",  # tryceratops
    "FLY",  # flynt
    "PERF", # perflint
]
# Python 3.9 compatibility: ignore modern type annotation rules
# TODO: Remove these ignores when dropping Python 3.9 support
ignore = [
    "UP007",  # Use X | Y for type annotations (requires Python 3.10+)
    "UP045",  # Use X | None for type annotations (requires Python 3.10+)
]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "PLR2004", "PLR0913"]  # assert文、マジックナンバー、関数引数数制限を許可

[format]
quote-style = "double"
indent-style = "space"
