name: Security Scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.9

    - name: Install dependencies
      run: uv sync

    - name: Run Ruff Security Rules
      run: |
        echo "::group::Running Ruff security scan (S* rules)"
        uv run ruff check --select=S --output-format=github
        echo "::endgroup::"

    - name: Check for known vulnerabilities with pip-audit
      run: |
        echo "::group::Running pip-audit for known vulnerabilities"
        uvx pip-audit --format=json --output=security-audit.json || true
        uvx pip-audit --format=markdown --output=security-audit.md || true
        echo "::endgroup::"

    - name: Upload security audit results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-audit-results
        path: |
          security-audit.json
          security-audit.md
        retention-days: 30

    - name: Security Summary
      if: always()
      run: |
        echo "## 🔒 Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Ruff Security Rules (S*)" >> $GITHUB_STEP_SUMMARY
        echo "✅ Ruff security scan completed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Dependency Vulnerability Check" >> $GITHUB_STEP_SUMMARY
        if [ -f "security-audit.md" ]; then
          echo "📄 Vulnerability scan results:" >> $GITHUB_STEP_SUMMARY
          cat security-audit.md >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ No known vulnerabilities found in dependencies" >> $GITHUB_STEP_SUMMARY
        fi
